sudo: required
dist: trusty
language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x cc-test-reporter
- "./cc-test-reporter before-build"
- sudo apt-get -qq update
- sudo apt-get install -yyq ca-certificates libappindicator1 libasound2 libatk1.0-0
  libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4
  libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0
  libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6
  libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 gconf-service lsb-release
  wget xdg-utils fonts-liberation -y
before_script:
- cp src/config.js.example src/config.js
- npm run lint
- npm run babel
script: npm run test
after_script:
- "./cc-test-reporter after-build --exit-code 0 -t lcov"
env:
  global:
    secure: IrTnrhF4FFHllSsd3SdieaY56lPasKrRNKsx+hDE1LFI1GLgssgpvif/NUCUUQW+XD9c/5BtVa4c24PU3oDNUcRxyOyFRqSvAGk7F/SW2LGn4KA2lfABKUGVSbztz80OtLis/2lPF2/mDLcrfhHtqGiC3JDcR9AZbctxQD61pDPwUW4YcXOs7+5p61RofJbIg4eOGWWavDpH77uqUTQ4LzmZ2klJMNt2uDR960olJUdN8JYPlRr4mpQh/XF1h4WDYZxhZarjTwAyTE2Lj5S+of9ySl5W8kEjXveTlEaOLvGTfYxqQTbatsLPm0uf3JTUrHNBD2qMPl2wAysbCkMhPo47352AjtUsFbpqWj/8cOSg1Qh1ktldjyI82MccFAjg8lxdrw57zWfWO3qbvsPSTV54gf/t1vGfNzhA1Ac821nJ+9Dvlmmgoj6AqcsmDwr8f9G3EcMJvzZtkz0j6O9XLYxu8B3INdJncutriUmCNPQR7AopYi5NZ8SGzsBf5V5XdHWjlp75cXxe7cA+QAOKFnXw+oxYNk9g6qWpFfyu8dF4InzBZlv+zgGBHzAr43m6muCL55aMHZwkq9n5pl9WWkgPQyRIkjmIi8VwPaRK0/Jxo1ZyN9xl1ORmrTbtWX1wLv2k508ZcwKDMG2xFT2rx+NU3XDL5mwhzT/Q56+F7BM=
notifications:
  slack:
    secure: YY4EGBU5Ofy+mxSYwHAPORsg5oNG81qCU/7JDsjqhe4HhbgGJhDssjmv8/uIqOiwkjsF0NXYEGvOPZwb7WSeegFHqQSUcyciR0Fyke1QMBimOXLzJbdnC9jjclE4RyQQ+zZG/Bx7PbXH2ty0XD/4uUl5ypeOR5Tl+/5sXTxCKTTcbMaV+Lp/6qm47A0o4pTnF9Q42reGolmLma3EMF0K3rN5aPYtG/t0fR8+CL5Xei0ewSZfdxvWTfjUx2DPwvuYmx5Tk2tVO5ssZrI7bsTaw7CXl2F+Ze4VRV4PdZSesIJNgEbbliqyqfPYgmj9ujvJ/5s+9wv4lU88dWFSUjpKc1GbOZFLhWGiAXtmDk90G/EfHm78YCfw5oypgas+UXDFitrhGDerPxIYmmLV9IkwwdWsyiksT3sgvHJyLkgckYcCzU45epP/io32qO2Xeq8JMouqQBrYuNvS0oa4EmqnEHFhxYtTzB1Fa1sY3112IP60poA5VFfeGD3i+KYCfTvXKuxjOxzuTfWypuNkzxGtRb7Qw7uhfvjWLDDdKFkgaTlon80EbZuoniktK77XDGfuH2y9h4KMKFqWZwQZ0Jsm1MJDzWYLmh+w5CvaON+MR8SB9kvx5bLyUPA9VMH13KOQz8aPYrRUgKiXPzAa6xuDG6icuunMgW0KXIlnfzLns1s=
