service: screenshot-as-a-service

provider:
    name: aws
    runtime: nodejs6.10
    memorySize: 1536
    timeout: 180
    # if needed (e.g. upload snapshot)
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "s3:upload"
          Resource: "arn:aws:s3:::techletter.app/*"

functions:
    screenshot-function:
        handler: index.handler
        environment:
            DEBUG: 0

package:
    artifact: ./package.zip

plugins:
    - serverless-hooks-plugin

custom:
    hooks:
        package:initialize:
            - npm run package
