service: narcissus-${env:ENV}

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2536
  timeout: 180
  apiKeys:
    - value: ${env:API_KEY}

functions:
  narcissus:
    handler: src/index.handler
    environment:
      DEBUG: 0
    events:
      - http:
          path: narcissus-${env:ENV}
          method: GET
          cors: true
          private: true
  narcissusAbout:
    handler: src/about.handler
    environment:
      DEBUG: 0
    events:
      - http:
          path: narcissus-${env:ENV}/about
          method: GET
          cors: true
          private: true

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - src/test.js
